#!/bin/bash

if [ -e '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist.bak' ]
  then
    rm '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist'
    mv '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist.bak' '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist'
    chown mobile '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist'
    chmod 0775 '/var/mobile/Library/Preferences/com.matchstic.winmoswitcher.plist'
    
fi